let originalRestDataList = {
  cards: [
    {
      id: "56166",
      name: "Mehtas (Old Delhi Original)",
      avgRating: 4.4,
      isOpen: true,
      cloudinaryImageId: "jfh1necyodxbhutskgpl",
    },
    {
      id: "25175",
      name: "BTW",
      avgRating: 4.1,
      isOpen: true,
      cloudinaryImageId: "dqxel3umlcwstdhmuco1",
    },
    {
      id: "387345",
      name: "Hotel Maidah",
      avgRating: 4.5,
      isOpen: true,
      cloudinaryImageId: "fx9cocswwgxh7qpcgekl",
    },
    {
      id: "34874",
      name: "United Coffee House",
      avgRating: 4.1,
      isOpen: true,
      cloudinaryImageId: "aaoj7d0mxiibecu8n08g",
    },
    {
      id: "202628",
      name: "Amritsariya",
      avgRating: 4.1,
      isOpen: true,
      cloudinaryImageId: "tp9jwftm7z5h4zornwhn",
    },
    {
      id: "330424",
      name: "The Pal's Kitchen",
      avgRating: 4.4,
      isOpen: true,
      cloudinaryImageId: "961d691102a367991e3772808d4444eb",
    },
    {
      id: "41345",
      name: "Shakahari Restaurant (Chawri Bazaar)",
      avgRating: 4.3,
      isOpen: true,
      cloudinaryImageId: "mcq1x7jllht0ggbbhogk",
    },
    {
      id: "40824",
      name: "Punjabi Zaika",
      avgRating: 4.1,
      isOpen: true,
      cloudinaryImageId: "kqjkegdihqhk1rvzpjhx",
    },
    {
      id: "42002",
      name: "Qureshi Kabab Corner",
      avgRating: 4,
      isOpen: true,
      cloudinaryImageId: "ws0dhfxtzmorh228lmoj",
    },
    {
      id: "452573",
      name: "DEEPAK DHABA",
      avgRating: 3.5,
      isOpen: true,
      cloudinaryImageId: "dhm1wsiriodemqf1wzu7",
    },
    {
      id: "41890",
      name: "Al Jawahar Restaurant (Jama Masjid)",
      avgRating: 4,
      isOpen: true,
      cloudinaryImageId: "l2hcl3u2g1cdgkz6kdd2",
    },
    {
      id: "659291",
      name: "Shivji'S Day Night Kitchen",
      avgRating: 3.8,
      isOpen: true,
      cloudinaryImageId: "a79403b3daea9a1ede0a7b1ec36bc943",
    },
    {
      id: "41739",
      name: "Zaika Foods",
      avgRating: 4.4,
      isOpen: true,
      cloudinaryImageId: "kahqrjqirhiw7ybctqzi",
    },
    {
      id: "821760",
      name: "Tadka Dhaba",
      avgRating: 3.6,
      isOpen: true,
      cloudinaryImageId: "43649026375c81ef3955c7c847623911",
    },
    {
      id: "44021",
      name: "Nazeer Foods",
      avgRating: 3.9,
      isOpen: true,
      cloudinaryImageId: "6aa38b251b1ee1662961a6dc19e41e95",
    },
  ],
};

export default originalRestDataList;